from abc import ABC, abstractmethod

from profyle.domain.trace import Trace, TraceCreate


class TraceRepository(ABC):
    @abstractmethod
    def create_trace_selected_table(self) -> None: ...

    @abstractmethod
    def create_trace_table(self) -> None: ...

    @abstractmethod
    def create_trace_file_table(self) -> None: ...

    @abstractmethod
    def create_trace_function_table(self) -> None: ...

    @abstractmethod
    def create_trace_event_table(self) -> None: ...

    @abstractmethod
    def create_trace_metadata_table(self) -> None: ...

    @abstractmethod
    def delete_all_traces(self) -> int: ...

    @abstractmethod
    def deleted_all_selected_traces(self) -> int: ...
    @abstractmethod
    def delete_all_trace_files(self) -> int: ...

    @abstractmethod
    def delete_all_trace_functions(self) -> int: ...

    @abstractmethod
    def delete_all_trace_events(self) -> int: ...

    @abstractmethod
    def delete_all_trace_metadata(self) -> int: ...

    @abstractmethod
    def vacuum(self) -> None: ...

    @abstractmethod
    def store_trace_selected(self, trace_id: int) -> None: ...

    @abstractmethod
    def store_trace(self, new_trace: TraceCreate) -> None: ...

    @abstractmethod
    def get_all_traces(self) -> list[Trace]: ...

    @abstractmethod
    def get_trace_by_id(self, id: int) -> Trace | None: ...

    @abstractmethod
    def get_trace_selected(self) -> int | None: ...

    @abstractmethod
    def delete_trace_by_id(self, trace_id: int): ...
